version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#   command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 6443:6443
      - 80:80
      - 81:81
      - 9000:9000
      - 9001:9001
    restart: unless-stopped

# networks:
#   docker-nginx:
#     name: network-nginx
#     driver: bridge
